### ISSUE TITLE
Better Representation of Axis

### ISSUE THREAD

**Issue by MrKangs** [ChatImproVR/chatimprovr#63]
In the Camera2D branch, I have created a new plugin called `xyz_reference` which shows what is the x, y, and z axis are based on the object location: it is a helper plugin for people who wants to place their object on certain location based on a frame. 

As of now, I set the solid lines as positive values of the certain whereas dotted lines as negative.

Red is X-axis, Green is Y-axis, and Blue s Z-axis. I am planning to put the blender for text of x, y, z to make it easy to read it. But is there any additional features that I should add into the plugin so that it will more useful?

**Comment by Masterchef365** [comment]
I think the current implementation looks good!
